version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fanta_auction_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: fanta_password
      POSTGRES_DB: fanta_auction
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: